<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitc95105aa153e4ceb6e5f9df953cb7a7c
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('PrettyLinks\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \PrettyLinks\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInitc95105aa153e4ceb6e5f9df953cb7a7c', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \PrettyLinks\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitc95105aa153e4ceb6e5f9df953cb7a7c', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\PrettyLinks\Composer\Autoload\ComposerStaticInitc95105aa153e4ceb6e5f9df953cb7a7c::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        $filesToLoad = \PrettyLinks\Composer\Autoload\ComposerStaticInitc95105aa153e4ceb6e5f9df953cb7a7c::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
